export const projects = [
  {
    id: "gas-station",
    name: "燃气站改造项目",
    type: "能源改造",
    manager: "王经理",
    stage: "设备基础施工",
    status: "有风险",
    aliases: ["燃气站", "站改造", "设备基础"],
    requiredDocs: ["施工方案", "隐蔽验收资料", "整改通知单", "周例会纪要", "安全交底"],
  },
  {
    id: "building-3",
    name: "3号楼主体结构项目",
    type: "房建",
    manager: "李工",
    stage: "主体结构",
    status: "正常推进",
    aliases: ["3号楼", "三号楼", "主体结构"],
    requiredDocs: ["施工方案", "混凝土浇筑记录", "试块报告", "周例会纪要", "安全交底"],
  },
  {
    id: "pipe-network",
    name: "市政管网更新项目",
    type: "市政",
    manager: "赵经理",
    stage: "沟槽开挖",
    status: "资料不完整",
    aliases: ["管网", "市政管网", "沟槽"],
    requiredDocs: ["施工方案", "交通导改方案", "沟槽验收记录", "周例会纪要", "安全交底"],
  },
];

export const processRecords = [
  {
    id: "wx-001",
    projectId: "gas-station",
    sourceType: "微信项目群",
    sourceName: "燃气站改造项目群",
    author: "张工",
    time: "2026-06-15 17:42",
    content: "燃气站改造项目今天完成设备基础浇筑，明天下午监理验收，施工单位周五前补交隐蔽验收资料。",
  },
  {
    id: "meeting-001",
    projectId: "gas-station",
    sourceType: "会议纪要",
    sourceName: "燃气站周例会纪要",
    author: "项目部",
    time: "2026-06-14 16:30",
    content: "会议要求施工单位6月17日前提交隐蔽验收资料，安全员复核临电箱整改照片，王经理跟进监理验收时间。",
  },
  {
    id: "file-001",
    projectId: "gas-station",
    sourceType: "工程文件",
    sourceName: "燃气站设备基础施工方案.pdf",
    author: "技术部",
    time: "2026-06-12 09:10",
    content: "设备基础施工方案，包含浇筑流程、隐蔽验收要求、试块留置要求和安全交底要求。",
  },
  {
    id: "wx-002",
    projectId: "building-3",
    sourceType: "微信项目群",
    sourceName: "3号楼施工群",
    author: "刘工",
    time: "2026-06-15 18:05",
    content: "3号楼今日浇筑混凝土120方，试块留置3组，未发现异常，明天继续绑扎十二层梁板钢筋。",
  },
  {
    id: "meeting-002",
    projectId: "building-3",
    sourceType: "会议纪要",
    sourceName: "3号楼周例会纪要",
    author: "项目部",
    time: "2026-06-13 15:00",
    content: "质量员周三前复核钢筋保护层；资料员补齐混凝土浇筑记录；安全员每天巡查临边防护。",
  },
  {
    id: "file-002",
    projectId: "building-3",
    sourceType: "工程文件",
    sourceName: "混凝土浇筑记录20260615.docx",
    author: "资料员",
    time: "2026-06-15 20:00",
    content: "3号楼浇筑记录：浇筑部位十一层梁板，方量120方，试块3组，坍落度记录齐全。",
  },
  {
    id: "wx-003",
    projectId: "pipe-network",
    sourceType: "微信项目群",
    sourceName: "市政管网更新群",
    author: "陈工",
    time: "2026-06-15 19:10",
    content: "市政管网今天完成K0+320至K0+480沟槽开挖，交通导改标识不足，明天上午补设。",
  },
  {
    id: "meeting-003",
    projectId: "pipe-network",
    sourceType: "会议纪要",
    sourceName: "管网安全专题会",
    author: "项目部",
    time: "2026-06-14 10:30",
    content: "会议要求赵经理6月15日前确认交通导改方案，施工队6月16日前补设围挡和警示灯，资料员补交沟槽验收记录。",
  },
];

export const tasks = [
  {
    id: "task-001",
    projectId: "gas-station",
    title: "补交隐蔽验收资料",
    owner: "施工单位",
    dueDate: "2026-06-19",
    status: "待处理",
    type: "资料缺失",
    sourceIds: ["wx-001", "meeting-001"],
    needsInfo: false,
  },
  {
    id: "task-002",
    projectId: "gas-station",
    title: "复核临电箱整改照片",
    owner: "安全员",
    dueDate: "2026-06-15",
    status: "逾期",
    type: "安全整改",
    sourceIds: ["meeting-001"],
    needsInfo: true,
  },
  {
    id: "task-003",
    projectId: "building-3",
    title: "补齐混凝土浇筑记录",
    owner: "资料员",
    dueDate: "2026-06-17",
    status: "已完成",
    type: "资料归档",
    sourceIds: ["meeting-002", "file-002"],
    needsInfo: false,
  },
  {
    id: "task-004",
    projectId: "building-3",
    title: "复核钢筋保护层",
    owner: "质量员",
    dueDate: "2026-06-17",
    status: "待处理",
    type: "质量检查",
    sourceIds: ["meeting-002"],
    needsInfo: false,
  },
  {
    id: "task-005",
    projectId: "pipe-network",
    title: "确认交通导改方案",
    owner: "赵经理",
    dueDate: "2026-06-15",
    status: "逾期",
    type: "协调事项",
    sourceIds: ["meeting-003"],
    needsInfo: true,
  },
  {
    id: "task-006",
    projectId: "pipe-network",
    title: "补设围挡和警示灯",
    owner: "施工队",
    dueDate: "2026-06-16",
    status: "逾期",
    type: "安全整改",
    sourceIds: ["wx-003", "meeting-003"],
    needsInfo: false,
  },
];

export const documents = [
  { id: "doc-001", projectId: "gas-station", name: "燃气站设备基础施工方案.pdf", type: "施工方案", status: "已归档", sourceId: "file-001" },
  { id: "doc-002", projectId: "gas-station", name: "燃气站周例会纪要.docx", type: "周例会纪要", status: "已归档", sourceId: "meeting-001" },
  { id: "doc-003", projectId: "gas-station", name: "隐蔽验收资料", type: "隐蔽验收资料", status: "缺失", sourceId: "wx-001" },
  { id: "doc-004", projectId: "building-3", name: "混凝土浇筑记录20260615.docx", type: "混凝土浇筑记录", status: "已归档", sourceId: "file-002" },
  { id: "doc-005", projectId: "building-3", name: "3号楼周例会纪要.docx", type: "周例会纪要", status: "已归档", sourceId: "meeting-002" },
  { id: "doc-006", projectId: "pipe-network", name: "交通导改方案", type: "交通导改方案", status: "缺失", sourceId: "meeting-003" },
  { id: "doc-007", projectId: "pipe-network", name: "沟槽验收记录", type: "沟槽验收记录", status: "缺失", sourceId: "meeting-003" },
];
