"""建立工程平台 PostgreSQL 基线

Revision ID: 6e8049fdaea3
Revises:
Create Date: 2026-08-13 14:59:34.548493
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '6e8049fdaea3'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级数据库结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_interaction_table_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('allowed_operations', sa.JSON(), nullable=False),
    sa.Column('readable_fields', sa.JSON(), nullable=False),
    sa.Column('writable_fields', sa.JSON(), nullable=False),
    sa.Column('filterable_fields', sa.JSON(), nullable=False),
    sa.Column('scope_type', sa.String(length=24), nullable=False),
    sa.Column('scope_field', sa.String(length=128), nullable=True),
    sa.Column('minimum_role', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("minimum_role IN ('member', 'admin')", name='ck_database_interaction_policy_minimum_role'),
    sa.CheckConstraint("scope_type IN ('project', 'user', 'global_admin')", name='ck_database_interaction_policy_scope_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_interaction_table_policies_enabled'), 'database_interaction_table_policies', ['enabled'], unique=False)
    op.create_index(op.f('ix_database_interaction_table_policies_table_name'), 'database_interaction_table_policies', ['table_name'], unique=True)
    op.create_table('platform_schema_versions',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('engineering_type_description', sa.Text(), nullable=True),
    sa.Column('contract_start_date', sa.Date(), nullable=True),
    sa.Column('contract_end_date', sa.Date(), nullable=True),
    sa.Column('contract_duration_days', sa.Integer(), nullable=True),
    sa.Column('contract_amount_wan_yuan', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('construction_unit_name', sa.String(length=300), nullable=True),
    sa.Column('general_contractor_unit_name', sa.String(length=300), nullable=True),
    sa.Column('supervision_unit_name', sa.String(length=300), nullable=True),
    sa.Column('design_unit_name', sa.String(length=300), nullable=True),
    sa.Column('survey_unit_name', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('contract_amount_wan_yuan IS NULL OR contract_amount_wan_yuan >= 0', name='ck_projects_contract_amount_nonnegative'),
    sa.CheckConstraint('contract_duration_days IS NULL OR contract_duration_days > 0', name='ck_projects_contract_duration_positive'),
    sa.CheckConstraint('contract_end_date IS NULL OR contract_start_date IS NULL OR contract_end_date >= contract_start_date', name='ck_projects_contract_date_order'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('real_name', sa.String(length=100), nullable=False),
    sa.Column('identity_card_no', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'user')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_card_no')
    )
    op.create_index('ix_users_real_name', 'users', ['real_name'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('agent_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('agent_name', sa.String(length=200), nullable=False),
    sa.Column('conversation_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('agentscope_session_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_conversations_agent_id'), 'agent_conversations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_conversations_agentscope_session_id'), 'agent_conversations', ['agentscope_session_id'], unique=True)
    op.create_index(op.f('ix_agent_conversations_conversation_type'), 'agent_conversations', ['conversation_type'], unique=False)
    op.create_index(op.f('ix_agent_conversations_project_id'), 'agent_conversations', ['project_id'], unique=False)
    op.create_index(op.f('ix_agent_conversations_user_id'), 'agent_conversations', ['user_id'], unique=False)
    op.create_index('uq_agent_conversations_project_user_initialization', 'agent_conversations', ['project_id', 'user_id'], unique=True, sqlite_where=sa.text("conversation_type = 'initialization'"), postgresql_where=sa.text("conversation_type = 'initialization'"))
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_file_hash'), 'attachments', ['file_hash'], unique=False)
    op.create_index(op.f('ix_attachments_project_id'), 'attachments', ['project_id'], unique=False)
    op.create_table('collaboration_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('participant_ids', sa.JSON(), nullable=False),
    sa.Column('task_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaboration_sessions_project_id'), 'collaboration_sessions', ['project_id'], unique=False)
    op.create_table('database_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('execution_kind', sa.String(length=16), nullable=False),
    sa.Column('builtin_operation', sa.String(length=128), nullable=True),
    sa.Column('table_policy_id', sa.Integer(), nullable=True),
    sa.Column('table_operation', sa.String(length=16), nullable=True),
    sa.Column('join_rules', sa.JSON(), nullable=False),
    sa.Column('context_bindings', sa.JSON(), nullable=False),
    sa.Column('fixed_values', sa.JSON(), nullable=False),
    sa.Column('runtime_policy', sa.JSON(), nullable=False),
    sa.Column('allowed_conversation_types', sa.JSON(), nullable=False),
    sa.Column('access_mode', sa.String(length=16), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('read_only', sa.Boolean(), nullable=False),
    sa.Column('requires_confirmation', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('built_in', sa.Boolean(), nullable=False),
    sa.Column('default_assigned', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("access_mode IN ('agent', 'workflow')", name='ck_database_interactions_access_mode'),
    sa.CheckConstraint("execution_kind IN ('builtin', 'table')", name='ck_database_interactions_execution_kind'),
    sa.CheckConstraint("table_operation IS NULL OR table_operation IN ('read', 'create', 'update', 'delete')", name='ck_database_interactions_table_operation'),
    sa.ForeignKeyConstraint(['table_policy_id'], ['database_interaction_table_policies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_interactions_enabled'), 'database_interactions', ['enabled'], unique=False)
    op.create_index('ix_database_interactions_enabled_sort', 'database_interactions', ['enabled', 'sort_order'], unique=False)
    op.create_index(op.f('ix_database_interactions_key'), 'database_interactions', ['key'], unique=True)
    op.create_index(op.f('ix_database_interactions_table_policy_id'), 'database_interactions', ['table_policy_id'], unique=False)
    op.create_table('document_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['document_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_folders_parent_id'), 'document_folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_document_folders_project_id'), 'document_folders', ['project_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_project_id'), 'notifications', ['project_id'], unique=False)
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_logs_project_id'), 'operation_logs', ['project_id'], unique=False)
    op.create_table('platform_field_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(length=200), nullable=False),
    sa.Column('source_field', sa.String(length=100), nullable=False),
    sa.Column('target_field', sa.String(length=200), nullable=False),
    sa.Column('transform_rule', sa.String(length=300), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_field_mappings_project_id'), 'platform_field_mappings', ['project_id'], unique=False)
    op.create_table('project_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_refs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_changes_project_id'), 'project_changes', ['project_id'], unique=False)
    op.create_table('project_information_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=300), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('recorded_at', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_refs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_information_records_project_id'), 'project_information_records', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'id', name='uq_project_member_project_id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member_user')
    )
    op.create_index('ix_project_members_project', 'project_members', ['project_id'], unique=False)
    op.create_index('ix_project_members_user', 'project_members', ['user_id'], unique=False)
    op.create_table('project_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('position_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'id', name='uq_project_position_project_id'),
    sa.UniqueConstraint('project_id', 'position_name', name='uq_project_position_name')
    )
    op.create_index('ix_project_positions_name', 'project_positions', ['position_name'], unique=False)
    op.create_index('ix_project_positions_project', 'project_positions', ['project_id'], unique=False)
    op.create_table('project_risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.Integer(), nullable=False),
    sa.Column('related_process_name', sa.String(length=300), nullable=False),
    sa.Column('risk_part', sa.String(length=300), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('evaluation_condition', sa.Text(), nullable=False),
    sa.Column('risk_window_start_date', sa.Date(), nullable=True),
    sa.Column('risk_window_end_date', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('risk_window_end_date IS NULL OR risk_window_start_date IS NULL OR risk_window_end_date >= risk_window_start_date', name='ck_project_risk_date_order'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'serial_no', name='uq_project_risk_serial')
    )
    op.create_index('ix_project_risk_level', 'project_risks', ['risk_level'], unique=False)
    op.create_index('ix_project_risk_project', 'project_risks', ['project_id'], unique=False)
    op.create_index('ix_project_risk_window', 'project_risks', ['risk_window_start_date', 'risk_window_end_date'], unique=False)
    op.create_table('project_settings',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('main_dir', sa.String(length=1000), nullable=True),
    sa.Column('archive_dir', sa.String(length=1000), nullable=True),
    sa.Column('temp_dir', sa.String(length=1000), nullable=True),
    sa.Column('failed_dir', sa.String(length=1000), nullable=True),
    sa.Column('backup_dir', sa.String(length=1000), nullable=True),
    sa.Column('scan_interval', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_rules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('project_status_snapshots',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('progress_rate', sa.Integer(), nullable=False),
    sa.Column('progress_status', sa.String(length=32), nullable=False),
    sa.Column('planned_delta', sa.String(length=64), nullable=False),
    sa.Column('risk_warnings', sa.Integer(), nullable=False),
    sa.Column('safety_issues', sa.Integer(), nullable=False),
    sa.Column('quality_issues', sa.Integer(), nullable=False),
    sa.Column('task_completion_rate', sa.Integer(), nullable=False),
    sa.Column('main_risk', sa.Text(), nullable=False),
    sa.Column('main_safety', sa.Text(), nullable=False),
    sa.Column('main_quality', sa.Text(), nullable=False),
    sa.Column('overall', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('project_wbs_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('color_value', sa.String(length=50), nullable=True),
    sa.Column('wbs_code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('assigned_to_text', sa.String(length=300), nullable=True),
    sa.Column('planned_start_at', sa.DateTime(), nullable=True),
    sa.Column('planned_finish_at', sa.DateTime(), nullable=True),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('duration_hours', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('time_log_minutes', sa.Integer(), nullable=True),
    sa.Column('status_text', sa.String(length=100), nullable=True),
    sa.Column('priority_text', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('msp_uid', sa.String(length=100), nullable=True),
    sa.Column('msp_id', sa.String(length=100), nullable=True),
    sa.Column('source_created_at', sa.DateTime(), nullable=True),
    sa.Column('source_creator', sa.String(length=200), nullable=True),
    sa.Column('item_type', sa.String(length=100), nullable=True),
    sa.Column('source_project_path', sa.Text(), nullable=True),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_cost IS NULL OR actual_cost >= 0', name='ck_wbs_actual_cost_nonnegative'),
    sa.CheckConstraint('budget IS NULL OR budget >= 0', name='ck_wbs_budget_nonnegative'),
    sa.CheckConstraint('duration_hours IS NULL OR duration_hours >= 0', name='ck_wbs_duration_nonnegative'),
    sa.CheckConstraint('estimated_hours IS NULL OR estimated_hours >= 0', name='ck_wbs_estimated_nonnegative'),
    sa.CheckConstraint('level > 0', name='ck_wbs_level_positive'),
    sa.CheckConstraint('parent_id IS NULL OR parent_id <> id', name='ck_wbs_not_self_parent'),
    sa.CheckConstraint('planned_finish_at IS NULL OR planned_start_at IS NULL OR planned_finish_at >= planned_start_at', name='ck_wbs_plan_date_order'),
    sa.CheckConstraint('progress_percent IS NULL OR (progress_percent >= 0 AND progress_percent <= 100)', name='ck_wbs_progress_range'),
    sa.CheckConstraint('sort_order >= 0', name='ck_wbs_sort_order_nonnegative'),
    sa.CheckConstraint('time_log_minutes IS NULL OR time_log_minutes >= 0', name='ck_wbs_time_log_nonnegative'),
    sa.ForeignKeyConstraint(['parent_id'], ['project_wbs_items.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'wbs_code', name='uq_project_wbs_code')
    )
    op.create_index('ix_project_wbs_level', 'project_wbs_items', ['project_id', 'level'], unique=False)
    op.create_index('ix_project_wbs_msp_id', 'project_wbs_items', ['msp_id'], unique=False)
    op.create_index('ix_project_wbs_msp_uid', 'project_wbs_items', ['msp_uid'], unique=False)
    op.create_index('ix_project_wbs_tree', 'project_wbs_items', ['project_id', 'parent_id', 'sort_order'], unique=False)
    op.create_table('attachment_texts',
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('parser', sa.String(length=100), nullable=True),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('parse_details', sa.JSON(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_index(op.f('ix_attachment_texts_project_id'), 'attachment_texts', ['project_id'], unique=False)
    op.create_table('collaboration_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generated_task_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['collaboration_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaboration_messages_session_id'), 'collaboration_messages', ['session_id'], unique=False)
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('report_date', sa.String(length=32), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('matched_wbs_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matched_wbs_id'], ['project_wbs_items.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_reports_project_id'), 'daily_reports', ['project_id'], unique=False)
    op.create_table('database_interaction_agent_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('assigned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['database_interactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'interaction_id', name='uq_database_interaction_agent_assignment')
    )
    op.create_index(op.f('ix_database_interaction_agent_assignments_interaction_id'), 'database_interaction_agent_assignments', ['interaction_id'], unique=False)
    op.create_index('ix_database_interaction_assignments_agent', 'database_interaction_agent_assignments', ['agent_id', 'assigned'], unique=False)
    op.create_table('document_folder_items',
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['document_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_index(op.f('ix_document_folder_items_folder_id'), 'document_folder_items', ['folder_id'], unique=False)
    op.create_index(op.f('ix_document_folder_items_project_id'), 'document_folder_items', ['project_id'], unique=False)
    op.create_table('meeting_minutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('action_items', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['collaboration_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_minutes_project_id'), 'meeting_minutes', ['project_id'], unique=False)
    op.create_index(op.f('ix_meeting_minutes_session_id'), 'meeting_minutes', ['session_id'], unique=False)
    op.create_table('project_initialization_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('validation_issues', sa.JSON(), nullable=False),
    sa.Column('source_files', sa.JSON(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('building', 'invalid', 'ready', 'applied', 'rejected')", name='ck_project_initialization_drafts_status'),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_initialization_drafts_conversation_id'), 'project_initialization_drafts', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_project_initialization_drafts_created_by_user_id'), 'project_initialization_drafts', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_project_initialization_drafts_project_id'), 'project_initialization_drafts', ['project_id'], unique=False)
    op.create_index('ix_project_initialization_drafts_project_status', 'project_initialization_drafts', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_project_initialization_drafts_status'), 'project_initialization_drafts', ['status'], unique=False)
    op.create_table('project_initialization_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('content_type', sa.String(length=200), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_initialization_files_conversation', 'project_initialization_files', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_project_initialization_files_conversation_id'), 'project_initialization_files', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_project_initialization_files_file_hash'), 'project_initialization_files', ['file_hash'], unique=False)
    op.create_index(op.f('ix_project_initialization_files_project_id'), 'project_initialization_files', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_initialization_files_uploaded_by_user_id'), 'project_initialization_files', ['uploaded_by_user_id'], unique=False)
    op.create_table('project_personnel_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_member_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.Integer(), nullable=False),
    sa.Column('certificate_no', sa.String(length=100), nullable=False),
    sa.Column('responsibility_description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'position_id'], ['project_positions.project_id', 'project_positions.id'], name='fk_personnel_assignment_position_project', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id', 'project_member_id'], ['project_members.project_id', 'project_members.id'], name='fk_personnel_assignment_member_project', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'serial_no', name='uq_project_personnel_serial'),
    sa.UniqueConstraint('project_member_id', 'position_id', name='uq_project_member_position')
    )
    op.create_index('ix_project_personnel_certificate', 'project_personnel_assignments', ['certificate_no'], unique=False)
    op.create_index('ix_project_personnel_member', 'project_personnel_assignments', ['project_member_id'], unique=False)
    op.create_index('ix_project_personnel_position', 'project_personnel_assignments', ['position_id'], unique=False)
    op.create_index('ix_project_personnel_project', 'project_personnel_assignments', ['project_id'], unique=False)
    op.create_table('project_wbs_predecessors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wbs_item_id', sa.Integer(), nullable=False),
    sa.Column('predecessor_wbs_item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('wbs_item_id <> predecessor_wbs_item_id', name='ck_wbs_predecessor_not_self'),
    sa.ForeignKeyConstraint(['predecessor_wbs_item_id'], ['project_wbs_items.id'], ),
    sa.ForeignKeyConstraint(['wbs_item_id'], ['project_wbs_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wbs_item_id', 'predecessor_wbs_item_id', name='uq_project_wbs_predecessor')
    )
    op.create_index('ix_wbs_predecessor_item', 'project_wbs_predecessors', ['wbs_item_id'], unique=False)
    op.create_index('ix_wbs_predecessor_predecessor', 'project_wbs_predecessors', ['predecessor_wbs_item_id'], unique=False)
    op.create_table('project_wbs_quality_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('wbs_code', sa.String(length=128), nullable=False),
    sa.Column('quality_acceptance_item', sa.Text(), nullable=False),
    sa.Column('control_indicator', sa.Text(), nullable=False),
    sa.Column('inspection_frequency', sa.Text(), nullable=False),
    sa.Column('related_documents', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'wbs_code'], ['project_wbs_items.project_id', 'project_wbs_items.wbs_code'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'wbs_code', name='uq_project_wbs_quality_requirement')
    )
    op.create_table('risk_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('risk_source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_refs', sa.JSON(), nullable=False),
    sa.Column('missing_items', sa.JSON(), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_source_id'], ['project_risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_drafts_project_id'), 'risk_drafts', ['project_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('confirmer_user_id', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.String(length=40), nullable=True),
    sa.Column('wbs_item_id', sa.Integer(), nullable=True),
    sa.Column('risk_source_id', sa.Integer(), nullable=True),
    sa.Column('trigger_reason', sa.Text(), nullable=True),
    sa.Column('required_materials', sa.JSON(), nullable=False),
    sa.Column('workflow_steps', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['confirmer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_source_id'], ['project_risks.id'], ),
    sa.ForeignKeyConstraint(['wbs_item_id'], ['project_wbs_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('wbs_risk_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('wbs_item_id', sa.Integer(), nullable=False),
    sa.Column('risk_source_id', sa.Integer(), nullable=False),
    sa.Column('alert_days', sa.Integer(), nullable=False),
    sa.Column('notify_methods', sa.JSON(), nullable=False),
    sa.Column('basis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_source_id'], ['project_risks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wbs_item_id'], ['project_wbs_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wbs_item_id', 'risk_source_id', name='uq_wbs_risk')
    )
    op.create_index(op.f('ix_wbs_risk_links_project_id'), 'wbs_risk_links', ['project_id'], unique=False)
    op.create_table('fill_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(length=200), nullable=False),
    sa.Column('process_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['risk_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fill_packages_project_id'), 'fill_packages', ['project_id'], unique=False)
    op.create_table('project_initialization_attachment_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('parser', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('parse_details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ready', 'failed')", name='ck_project_initialization_attachment_chunks_status'),
    sa.CheckConstraint('chunk_index >= 0 AND chunk_count >= 1', name='ck_project_initialization_attachment_chunks_position'),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['project_initialization_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'chunk_index', name='uq_project_initialization_attachment_chunks_position')
    )
    op.create_index(op.f('ix_project_initialization_attachment_chunks_content_hash'), 'project_initialization_attachment_chunks', ['content_hash'], unique=False)
    op.create_index('ix_project_initialization_attachment_chunks_conversation', 'project_initialization_attachment_chunks', ['conversation_id', 'file_id', 'chunk_index'], unique=False)
    op.create_index(op.f('ix_project_initialization_attachment_chunks_conversation_id'), 'project_initialization_attachment_chunks', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_project_initialization_attachment_chunks_file_id'), 'project_initialization_attachment_chunks', ['file_id'], unique=False)
    op.create_index(op.f('ix_project_initialization_attachment_chunks_project_id'), 'project_initialization_attachment_chunks', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_initialization_attachment_chunks_status'), 'project_initialization_attachment_chunks', ['status'], unique=False)
    op.create_table('project_initialization_draft_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=40), nullable=False),
    sa.Column('writer_agent_id', sa.String(length=128), nullable=False),
    sa.Column('workflow_revision', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('source_files', sa.JSON(), nullable=False),
    sa.Column('extraction_notes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("section IN ('project', 'personnel', 'wbs', 'risks', 'quality_requirements')", name='ck_project_initialization_draft_sections_section'),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['draft_id'], ['project_initialization_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', 'section', name='uq_project_initialization_draft_sections_draft_section')
    )
    op.create_index(op.f('ix_project_initialization_draft_sections_conversation_id'), 'project_initialization_draft_sections', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_project_initialization_draft_sections_draft_id'), 'project_initialization_draft_sections', ['draft_id'], unique=False)
    op.create_index('ix_project_initialization_draft_sections_project', 'project_initialization_draft_sections', ['project_id', 'draft_id'], unique=False)
    op.create_index(op.f('ix_project_initialization_draft_sections_project_id'), 'project_initialization_draft_sections', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_initialization_draft_sections_writer_agent_id'), 'project_initialization_draft_sections', ['writer_agent_id'], unique=False)
    op.create_table('project_initialization_validation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('draft_revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('result_status', sa.String(length=24), nullable=True),
    sa.Column('package_id', sa.String(length=128), nullable=True),
    sa.Column('package_version', sa.String(length=64), nullable=True),
    sa.Column('ruleset_version', sa.String(length=64), nullable=True),
    sa.Column('validation_issues', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("result_status IS NULL OR result_status IN ('ready', 'invalid')", name='ck_project_initialization_validation_runs_result_status'),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed')", name='ck_project_initialization_validation_runs_status'),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['draft_id'], ['project_initialization_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_initialization_validation_runs_conversation_id'), 'project_initialization_validation_runs', ['conversation_id'], unique=False)
    op.create_index('ix_project_initialization_validation_runs_draft', 'project_initialization_validation_runs', ['draft_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_project_initialization_validation_runs_draft_id'), 'project_initialization_validation_runs', ['draft_id'], unique=False)
    op.create_index(op.f('ix_project_initialization_validation_runs_project_id'), 'project_initialization_validation_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_initialization_validation_runs_status'), 'project_initialization_validation_runs', ['status'], unique=False)
    op.create_table('task_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_status_history_task_id'), 'task_status_history', ['task_id'], unique=False)
    op.create_table('project_initialization_draft_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=40), nullable=False),
    sa.Column('section_revision', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('business_key', sa.String(length=300), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("section IN ('project', 'personnel', 'wbs', 'risks', 'quality_requirements')", name='ck_project_initialization_draft_records_section'),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['draft_id'], ['project_initialization_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['project_initialization_draft_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'ordinal', name='uq_project_initialization_draft_records_section_ordinal')
    )
    op.create_index(op.f('ix_project_initialization_draft_records_active'), 'project_initialization_draft_records', ['active'], unique=False)
    op.create_index(op.f('ix_project_initialization_draft_records_conversation_id'), 'project_initialization_draft_records', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_project_initialization_draft_records_draft_id'), 'project_initialization_draft_records', ['draft_id'], unique=False)
    op.create_index('ix_project_initialization_draft_records_draft_section', 'project_initialization_draft_records', ['draft_id', 'section', 'ordinal'], unique=False)
    op.create_index(op.f('ix_project_initialization_draft_records_project_id'), 'project_initialization_draft_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_initialization_draft_records_section_id'), 'project_initialization_draft_records', ['section_id'], unique=False)
    op.create_table('project_initialization_validation_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('validation_run_id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('draft_revision', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=40), nullable=False),
    sa.Column('target_record_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=128), nullable=True),
    sa.Column('rule_id', sa.String(length=200), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('related_record_ids', sa.JSON(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("level IN ('error', 'warning')", name='ck_project_initialization_validation_issues_level'),
    sa.CheckConstraint("section IN ('project', 'personnel', 'wbs', 'risks', 'quality_requirements')", name='ck_project_initialization_validation_issues_section'),
    sa.ForeignKeyConstraint(['draft_id'], ['project_initialization_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_record_id'], ['project_initialization_draft_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['validation_run_id'], ['project_initialization_validation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_initialization_validation_issues_draft_id'), 'project_initialization_validation_issues', ['draft_id'], unique=False)
    op.create_index('ix_project_initialization_validation_issues_draft_target', 'project_initialization_validation_issues', ['draft_id', 'target_record_id', 'field_name'], unique=False)
    op.create_index(op.f('ix_project_initialization_validation_issues_project_id'), 'project_initialization_validation_issues', ['project_id'], unique=False)
    op.create_index('ix_project_initialization_validation_issues_run', 'project_initialization_validation_issues', ['validation_run_id', 'id'], unique=False)
    op.create_index(op.f('ix_project_initialization_validation_issues_target_record_id'), 'project_initialization_validation_issues', ['target_record_id'], unique=False)
    op.create_index(op.f('ix_project_initialization_validation_issues_validation_run_id'), 'project_initialization_validation_issues', ['validation_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回退数据库结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_initialization_validation_issues_validation_run_id'), table_name='project_initialization_validation_issues')
    op.drop_index(op.f('ix_project_initialization_validation_issues_target_record_id'), table_name='project_initialization_validation_issues')
    op.drop_index('ix_project_initialization_validation_issues_run', table_name='project_initialization_validation_issues')
    op.drop_index(op.f('ix_project_initialization_validation_issues_project_id'), table_name='project_initialization_validation_issues')
    op.drop_index('ix_project_initialization_validation_issues_draft_target', table_name='project_initialization_validation_issues')
    op.drop_index(op.f('ix_project_initialization_validation_issues_draft_id'), table_name='project_initialization_validation_issues')
    op.drop_table('project_initialization_validation_issues')
    op.drop_index(op.f('ix_project_initialization_draft_records_section_id'), table_name='project_initialization_draft_records')
    op.drop_index(op.f('ix_project_initialization_draft_records_project_id'), table_name='project_initialization_draft_records')
    op.drop_index('ix_project_initialization_draft_records_draft_section', table_name='project_initialization_draft_records')
    op.drop_index(op.f('ix_project_initialization_draft_records_draft_id'), table_name='project_initialization_draft_records')
    op.drop_index(op.f('ix_project_initialization_draft_records_conversation_id'), table_name='project_initialization_draft_records')
    op.drop_index(op.f('ix_project_initialization_draft_records_active'), table_name='project_initialization_draft_records')
    op.drop_table('project_initialization_draft_records')
    op.drop_index(op.f('ix_task_status_history_task_id'), table_name='task_status_history')
    op.drop_table('task_status_history')
    op.drop_index(op.f('ix_project_initialization_validation_runs_status'), table_name='project_initialization_validation_runs')
    op.drop_index(op.f('ix_project_initialization_validation_runs_project_id'), table_name='project_initialization_validation_runs')
    op.drop_index(op.f('ix_project_initialization_validation_runs_draft_id'), table_name='project_initialization_validation_runs')
    op.drop_index('ix_project_initialization_validation_runs_draft', table_name='project_initialization_validation_runs')
    op.drop_index(op.f('ix_project_initialization_validation_runs_conversation_id'), table_name='project_initialization_validation_runs')
    op.drop_table('project_initialization_validation_runs')
    op.drop_index(op.f('ix_project_initialization_draft_sections_writer_agent_id'), table_name='project_initialization_draft_sections')
    op.drop_index(op.f('ix_project_initialization_draft_sections_project_id'), table_name='project_initialization_draft_sections')
    op.drop_index('ix_project_initialization_draft_sections_project', table_name='project_initialization_draft_sections')
    op.drop_index(op.f('ix_project_initialization_draft_sections_draft_id'), table_name='project_initialization_draft_sections')
    op.drop_index(op.f('ix_project_initialization_draft_sections_conversation_id'), table_name='project_initialization_draft_sections')
    op.drop_table('project_initialization_draft_sections')
    op.drop_index(op.f('ix_project_initialization_attachment_chunks_status'), table_name='project_initialization_attachment_chunks')
    op.drop_index(op.f('ix_project_initialization_attachment_chunks_project_id'), table_name='project_initialization_attachment_chunks')
    op.drop_index(op.f('ix_project_initialization_attachment_chunks_file_id'), table_name='project_initialization_attachment_chunks')
    op.drop_index(op.f('ix_project_initialization_attachment_chunks_conversation_id'), table_name='project_initialization_attachment_chunks')
    op.drop_index('ix_project_initialization_attachment_chunks_conversation', table_name='project_initialization_attachment_chunks')
    op.drop_index(op.f('ix_project_initialization_attachment_chunks_content_hash'), table_name='project_initialization_attachment_chunks')
    op.drop_table('project_initialization_attachment_chunks')
    op.drop_index(op.f('ix_fill_packages_project_id'), table_name='fill_packages')
    op.drop_table('fill_packages')
    op.drop_index(op.f('ix_wbs_risk_links_project_id'), table_name='wbs_risk_links')
    op.drop_table('wbs_risk_links')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_risk_drafts_project_id'), table_name='risk_drafts')
    op.drop_table('risk_drafts')
    op.drop_table('project_wbs_quality_requirements')
    op.drop_index('ix_wbs_predecessor_predecessor', table_name='project_wbs_predecessors')
    op.drop_index('ix_wbs_predecessor_item', table_name='project_wbs_predecessors')
    op.drop_table('project_wbs_predecessors')
    op.drop_index('ix_project_personnel_project', table_name='project_personnel_assignments')
    op.drop_index('ix_project_personnel_position', table_name='project_personnel_assignments')
    op.drop_index('ix_project_personnel_member', table_name='project_personnel_assignments')
    op.drop_index('ix_project_personnel_certificate', table_name='project_personnel_assignments')
    op.drop_table('project_personnel_assignments')
    op.drop_index(op.f('ix_project_initialization_files_uploaded_by_user_id'), table_name='project_initialization_files')
    op.drop_index(op.f('ix_project_initialization_files_project_id'), table_name='project_initialization_files')
    op.drop_index(op.f('ix_project_initialization_files_file_hash'), table_name='project_initialization_files')
    op.drop_index(op.f('ix_project_initialization_files_conversation_id'), table_name='project_initialization_files')
    op.drop_index('ix_project_initialization_files_conversation', table_name='project_initialization_files')
    op.drop_table('project_initialization_files')
    op.drop_index(op.f('ix_project_initialization_drafts_status'), table_name='project_initialization_drafts')
    op.drop_index('ix_project_initialization_drafts_project_status', table_name='project_initialization_drafts')
    op.drop_index(op.f('ix_project_initialization_drafts_project_id'), table_name='project_initialization_drafts')
    op.drop_index(op.f('ix_project_initialization_drafts_created_by_user_id'), table_name='project_initialization_drafts')
    op.drop_index(op.f('ix_project_initialization_drafts_conversation_id'), table_name='project_initialization_drafts')
    op.drop_table('project_initialization_drafts')
    op.drop_index(op.f('ix_meeting_minutes_session_id'), table_name='meeting_minutes')
    op.drop_index(op.f('ix_meeting_minutes_project_id'), table_name='meeting_minutes')
    op.drop_table('meeting_minutes')
    op.drop_index(op.f('ix_document_folder_items_project_id'), table_name='document_folder_items')
    op.drop_index(op.f('ix_document_folder_items_folder_id'), table_name='document_folder_items')
    op.drop_table('document_folder_items')
    op.drop_index('ix_database_interaction_assignments_agent', table_name='database_interaction_agent_assignments')
    op.drop_index(op.f('ix_database_interaction_agent_assignments_interaction_id'), table_name='database_interaction_agent_assignments')
    op.drop_table('database_interaction_agent_assignments')
    op.drop_index(op.f('ix_daily_reports_project_id'), table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_index(op.f('ix_collaboration_messages_session_id'), table_name='collaboration_messages')
    op.drop_table('collaboration_messages')
    op.drop_index(op.f('ix_attachment_texts_project_id'), table_name='attachment_texts')
    op.drop_table('attachment_texts')
    op.drop_index('ix_project_wbs_tree', table_name='project_wbs_items')
    op.drop_index('ix_project_wbs_msp_uid', table_name='project_wbs_items')
    op.drop_index('ix_project_wbs_msp_id', table_name='project_wbs_items')
    op.drop_index('ix_project_wbs_level', table_name='project_wbs_items')
    op.drop_table('project_wbs_items')
    op.drop_table('project_status_snapshots')
    op.drop_table('project_settings')
    op.drop_index('ix_project_risk_window', table_name='project_risks')
    op.drop_index('ix_project_risk_project', table_name='project_risks')
    op.drop_index('ix_project_risk_level', table_name='project_risks')
    op.drop_table('project_risks')
    op.drop_index('ix_project_positions_project', table_name='project_positions')
    op.drop_index('ix_project_positions_name', table_name='project_positions')
    op.drop_table('project_positions')
    op.drop_index('ix_project_members_user', table_name='project_members')
    op.drop_index('ix_project_members_project', table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_project_information_records_project_id'), table_name='project_information_records')
    op.drop_table('project_information_records')
    op.drop_index(op.f('ix_project_changes_project_id'), table_name='project_changes')
    op.drop_table('project_changes')
    op.drop_index(op.f('ix_platform_field_mappings_project_id'), table_name='platform_field_mappings')
    op.drop_table('platform_field_mappings')
    op.drop_index(op.f('ix_operation_logs_project_id'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index(op.f('ix_notifications_project_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_document_folders_project_id'), table_name='document_folders')
    op.drop_index(op.f('ix_document_folders_parent_id'), table_name='document_folders')
    op.drop_table('document_folders')
    op.drop_index(op.f('ix_database_interactions_table_policy_id'), table_name='database_interactions')
    op.drop_index(op.f('ix_database_interactions_key'), table_name='database_interactions')
    op.drop_index('ix_database_interactions_enabled_sort', table_name='database_interactions')
    op.drop_index(op.f('ix_database_interactions_enabled'), table_name='database_interactions')
    op.drop_table('database_interactions')
    op.drop_index(op.f('ix_collaboration_sessions_project_id'), table_name='collaboration_sessions')
    op.drop_table('collaboration_sessions')
    op.drop_index(op.f('ix_attachments_project_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_file_hash'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('uq_agent_conversations_project_user_initialization', table_name='agent_conversations', sqlite_where=sa.text("conversation_type = 'initialization'"), postgresql_where=sa.text("conversation_type = 'initialization'"))
    op.drop_index(op.f('ix_agent_conversations_user_id'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_project_id'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_conversation_type'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_agentscope_session_id'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_agent_id'), table_name='agent_conversations')
    op.drop_table('agent_conversations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_real_name', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('platform_schema_versions')
    op.drop_index(op.f('ix_database_interaction_table_policies_table_name'), table_name='database_interaction_table_policies')
    op.drop_index(op.f('ix_database_interaction_table_policies_enabled'), table_name='database_interaction_table_policies')
    op.drop_table('database_interaction_table_policies')
    # ### end Alembic commands ###
