# -*- coding: utf-8 -*-
"""Initial schema — frozen snapshot of every table in ``_sql/_tables.py``.

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-20 10:24:57.000000

This revision is a *static snapshot*: the ``op.create_table`` calls are
frozen at the schema as it stood when the SQL backend first shipped.
It deliberately does NOT delegate to ``_Base.metadata.create_all`` —
doing so would make the initial revision track the *current* metadata,
so a later column/table addition would be created here (on a fresh
database) and then created *again* by its own autogenerated revision,
which fails as a duplicate. Every future schema change must be added
as a new ``alembic revision --autogenerate`` on top of this one.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create every table at the first-shipped schema."""
    op.create_table(
        "agents",
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_agents_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_agents_source"),
            ["source"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_agents_updated_at"),
            ["updated_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_agents_user_id"),
            ["user_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_agents_user_source",
            ["user_id", "source"],
            unique=False,
        )

    op.create_table(
        "credentials",
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("credentials", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_credentials_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_credentials_updated_at"),
            ["updated_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_credentials_user_id"),
            ["user_id"],
            unique=False,
        )

    op.create_table(
        "knowledge_bases",
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("knowledge_bases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_knowledge_bases_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_knowledge_bases_updated_at"),
            ["updated_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_knowledge_bases_user_id"),
            ["user_id"],
            unique=False,
        )

    op.create_table(
        "messages",
        sa.Column("session_id", sa.String(length=255), nullable=False),
        sa.Column("msg_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("session_id", "msg_id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_messages_session_created",
            ["session_id", "created_at"],
            unique=False,
        )

    op.create_table(
        "schedules",
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("agent_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("schedules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_schedules_agent_id"),
            ["agent_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_schedules_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_schedules_updated_at"),
            ["updated_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_schedules_user_id"),
            ["user_id"],
            unique=False,
        )

    op.create_table(
        "sessions",
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("agent_id", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column(
            "source_schedule_id",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column("team_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sessions_agent_id"),
            ["agent_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_sessions_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_sessions_source"),
            ["source"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_sessions_source_schedule_id"),
            ["source_schedule_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_sessions_team_id"),
            ["team_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_sessions_updated_at"),
            ["updated_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_sessions_user_agent",
            ["user_id", "agent_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_sessions_user_id"),
            ["user_id"],
            unique=False,
        )

    op.create_table(
        "teams",
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_teams_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_teams_updated_at"),
            ["updated_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_teams_user_id"),
            ["user_id"],
            unique=False,
        )

    op.create_table(
        "knowledge_documents",
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column(
            "knowledge_base_id",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "processing_node",
            sa.String(length=128),
            nullable=True,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"],
            ["knowledge_bases.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table(
        "knowledge_documents",
        schema=None,
    ) as batch_op:
        batch_op.create_index(
            "ix_kd_status_lease",
            ["status", "lease_expires_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_kd_user_kb",
            ["user_id", "knowledge_base_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_knowledge_documents_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_knowledge_documents_knowledge_base_id"),
            ["knowledge_base_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_knowledge_documents_status"),
            ["status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_knowledge_documents_updated_at"),
            ["updated_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_knowledge_documents_user_id"),
            ["user_id"],
            unique=False,
        )


def downgrade() -> None:
    """Drop every table created by :func:`upgrade`."""
    with op.batch_alter_table(
        "knowledge_documents",
        schema=None,
    ) as batch_op:
        batch_op.drop_index(batch_op.f("ix_knowledge_documents_user_id"))
        batch_op.drop_index(batch_op.f("ix_knowledge_documents_updated_at"))
        batch_op.drop_index(batch_op.f("ix_knowledge_documents_status"))
        batch_op.drop_index(
            batch_op.f("ix_knowledge_documents_knowledge_base_id"),
        )
        batch_op.drop_index(batch_op.f("ix_knowledge_documents_created_at"))
        batch_op.drop_index("ix_kd_user_kb")
        batch_op.drop_index("ix_kd_status_lease")
    op.drop_table("knowledge_documents")

    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_teams_user_id"))
        batch_op.drop_index(batch_op.f("ix_teams_updated_at"))
        batch_op.drop_index(batch_op.f("ix_teams_created_at"))
    op.drop_table("teams")

    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))
        batch_op.drop_index("ix_sessions_user_agent")
        batch_op.drop_index(batch_op.f("ix_sessions_updated_at"))
        batch_op.drop_index(batch_op.f("ix_sessions_team_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_source_schedule_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_source"))
        batch_op.drop_index(batch_op.f("ix_sessions_created_at"))
        batch_op.drop_index(batch_op.f("ix_sessions_agent_id"))
    op.drop_table("sessions")

    with op.batch_alter_table("schedules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_schedules_user_id"))
        batch_op.drop_index(batch_op.f("ix_schedules_updated_at"))
        batch_op.drop_index(batch_op.f("ix_schedules_created_at"))
        batch_op.drop_index(batch_op.f("ix_schedules_agent_id"))
    op.drop_table("schedules")

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index("ix_messages_session_created")
    op.drop_table("messages")

    with op.batch_alter_table("knowledge_bases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_knowledge_bases_user_id"))
        batch_op.drop_index(batch_op.f("ix_knowledge_bases_updated_at"))
        batch_op.drop_index(batch_op.f("ix_knowledge_bases_created_at"))
    op.drop_table("knowledge_bases")

    with op.batch_alter_table("credentials", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_credentials_user_id"))
        batch_op.drop_index(batch_op.f("ix_credentials_updated_at"))
        batch_op.drop_index(batch_op.f("ix_credentials_created_at"))
    op.drop_table("credentials")

    with op.batch_alter_table("agents", schema=None) as batch_op:
        batch_op.drop_index("ix_agents_user_source")
        batch_op.drop_index(batch_op.f("ix_agents_user_id"))
        batch_op.drop_index(batch_op.f("ix_agents_updated_at"))
        batch_op.drop_index(batch_op.f("ix_agents_source"))
        batch_op.drop_index(batch_op.f("ix_agents_created_at"))
    op.drop_table("agents")
